name: Release extension
on:
  push:
    branches:
      - master
    tags:
      -v*
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run prod
      - name: Publish to WebStore
        uses: Klemensas/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: '${{ secrets.REFRESH_TOKEN }}'
          client-id: '${{ secrets.CLIENT_ID }}'
          client-secret: '${{ secrets.CLIENT_SECRET }}'
          file-name: './dist.zip'
          app-id: '${{ secrets.APP_ID }}'
          publish: true
